### PR TITLE
removed leading spaces in combined certificate generation

### PR DESCRIPTION
**Pull request by llonchj**
nginx does not handle a combined certificate with leading spaces

### CODE REVIEW

**Comment by pdf** [comment]
:+1: 

Broken certs are nobody's friend.

**Comment by cap10morgan** [comment]
Sorry for the delay on this. I must have missed the original notification. Thanks for the PR, @llonchj and thanks for the ping, @pdf. I'll push a release to the cookbook site.

**Comment by cap10morgan** [comment]
1.0.8 is live: http://community.opscode.com/cookbooks/ssl

**Comment by llonchj** [comment]
you're welcome. Thanks for the cookbook

**Pull request merged**
