### PR TITLE
Add rhel to supported os'es

### PR DESCRIPTION
**Pull request by miry**
squashed PR #5

### CODE REVIEW

**Comment by sanguis** [comment]
I had to to read the queue to find out if it supported Red Hat so I though why not just add it to the readme.

**Comment by cap10morgan** [comment]
@sanguis There are still fixes that need to be made to this PR before it can be merged. They're very minor, but as I don't use RHEL, I would need someone who does to apply the fixes and help me maintain RHEL support in the future before I would claim to support it in the README.

If you'd like to be that person, feel free to start w/ this branch, apply the fixes I outline above (or argue for something different), and then submit a new PR.

**Comment by sanguis** [comment]
@cap10morgan I guess I will have to test then.

**Comment by cap10morgan** [comment]
I'm closing this PR without merge in 7 days. If anyone wants to help test and support RHEL, CentOS, etc. please do so before then.

**Pull request closed without merging**
