### PR TITLE
Use data bag item instead of Encrypted Item. Added ability to filter cert by domain.

### PR DESCRIPTION
**Pull request by miry**
Added ability to filter certificates. Use simple data bag item instead only encrypted.

### CODE REVIEW

**Comment by cap10morgan** [comment]
Private keys should be in an encrypted data bag. So I won't be merging this.

**Comment by miry** [comment]
> Private keys should be in an encrypted data bag. So I won't be merging this.

yes you are right, but better give developers to choose the method to store the certificates, instead of just use encryption.

**Comment by miry** [comment]
also I updated read me, because I waste a ton of time to understand how it works. Until I did not look to code, the read me did not help me.

**Comment by cap10morgan** [comment]
I don't believe it is better to give developers that choice. What's the use case?

If you submit another pull request with just your README changes, I can review those separately. Thanks!

**Comment by miry** [comment]
@cap10morgan I have created #9. pls verify, thanks.

**Pull request closed without merging**
